Algoritmo "correçaoatividadedeaula01"

Var
numero ,antecessor: Inteiro

Inicio
// 1) Escreva um algoritmo para ler um valor e escrever seu antecesor
// Entrada
//Receber um numero
 escreval ( "Digite um numero para verificar antecesor " )
leia (numero)

//Proceso
//Numero -1
 antecessor <-numero -1
 
// numero -1
//saida
//Escrever o antecessor
Limpatela
escreval ("O antecessor do numero",numero,"e ",antecessor)


Fimalgoritmo