Algoritmo "aula 04-correçao ex3"
// Disciplina
Var
// Seção de Declarações das variáveis

contador: inteiro

Inicio
//Processo
//repetiçao de 10
// (contador > 0) e contador < 10)
contador <- 1
escreval (contador <= 10) faça
 escreval contador ("8 x " contador, " = "contador * 8)
contador  <- contador +1
fimEnquanto


 escreval (contador)
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Fimalgoritmo