Algoritmo "EXEMPLO AULA 03"

//
//INFOS QUE JA ESTAO SALVAS
usuarioSalvo,senhaSalva: caractere

usuarioSalvo<- "fulano"


usuarioSalva <- "senha123"
senhaSalvo <- "senha123"
UsuarioSalvo<- "FULANO"


leia (usuario)

escreval ( usuarioSalvo=<-"fulano"
leia (senha)
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
se (usuarioSalvo=usuario) e (senhaSalva=senha) entao
escreval("login efetuado com sucesso!")
fimSe
escreval ("Usuario ou senha incorretos"



Fimalgoritmo